#!/usr/bin/env python3
"""
Daily Ticket Generator — Sysadmin Practice Workflow
Generates a daily sysadmin ticket for a lab practice environment.
Designed to run via cron 30 minutes before "shift" start.

Usage:
    python3 generate_daily_ticket.py

Configuration:
    - Set TICKETS_DIR to your ticket output directory
    - Set START_DATE to the Monday of Week 1
    - Customize the SCHEDULE dict with your own task rotation

Author: Network Foundry Project
"""

import os
from datetime import datetime

# === Configuration ===
TICKETS_DIR = "./tickets"  # Change to your ticket output directory
START_DATE = datetime(2026, 7, 21)  # Week 1 Monday

# === Morning Checkup Template (same every day) ===
MORNING_CHECKUP = """## Morning Checkup

Complete this before starting the ticket work.

### Server Health

```bash
sudo systemctl status samba-ad-dc
sudo systemctl status isc-dhcp-server
sudo systemctl status cups
sudo ss -tlnp | grep :53
sudo ss -tlnp | grep :631
ip route show
ping -c 3 8.8.8.8
```

- [ ] All three services active (running)?
- [ ] DNS listening on correct interface?
- [ ] CUPS listening on 0.0.0.0:631?
- [ ] All routes present?
- [ ] Internet reachable?

### Network Health

```bash
# Ping all lab devices
ping -c 3 <server_ip>
ping -c 3 <router_ip>
ping -c 3 <switch_ip>
```

- [ ] All lab devices reachable?

### Client Health

```bash
# On a domain-joined client
ip route show
resolvectl status
ping -c 3 google.com
id FOUNDRY\\\\<user>
```

- [ ] Gateway correct?
- [ ] DNS correct?
- [ ] Internet working?
- [ ] Domain users visible?

### Security Check

```bash
sudo journalctl -u ssh -n 50 --no-pager | grep -i "failed\\|invalid"
sudo ufw status numbered
```

- [ ] Any unusual login attempts?
- [ ] Firewall rules intact?

### Log Review

```bash
sudo journalctl -p err -n 20 --no-pager
sudo journalctl -u samba-ad-dc -n 20 --no-pager | grep -i "error\\|fail\\|warn"
```

- [ ] Any errors in system logs?

### Morning Summary

```
Date: __________
Server: pass / fail
Network: pass / fail
Client: pass / fail
Security: pass / fail
Issues found: __________
```

---
"""

# === End of Day Template ===
END_OF_DAY = """
---

## End of Day

```
Ticket {ticket_id} Status: Completed / In Progress / Blocked
Time spent: __________
Issues encountered: __________
What I learned: __________
```

---

*Generated by generate_daily_ticket.py*
"""

# === Weekly Task Schedule ===
# Days: 0=Monday, 1=Tuesday, ..., 6=Sunday
# Customize this with your own tasks

SCHEDULE = {
    1: {  # Week 1 — Fundamentals
        0: {"area": "Documentation & Maintenance", "prefix": "DOC",
             "description": "Review and update all lab documentation.",
             "tasks": "- [ ] Verify all IP addresses match running config\n- [ ] Update change log\n- [ ] Add entries for new services"},
        1: {"area": "User Management", "prefix": "USR",
             "description": "Create users for different departments, create groups, assign users.",
             "tasks": "- [ ] Create 3 users with samba-tool\n- [ ] Create 3 department groups\n- [ ] Assign users to groups\n- [ ] Verify from client with id FOUNDRY\\\\user\n- [ ] Test with kinit"},
        2: {"area": "DNS Management", "prefix": "DNS",
             "description": "Add DNS records for all lab devices, add CNAME aliases, test resolution.",
             "tasks": "- [ ] Add A records for all devices\n- [ ] Add CNAME aliases\n- [ ] Verify from server and client\n- [ ] Ping by hostname"},
        3: {"area": "File Services", "prefix": "FIL",
             "description": "Create department shares with group permissions, create home drives, test access.",
             "tasks": "- [ ] Create department share directories\n- [ ] Configure smb.conf with valid users\n- [ ] Create personal home drives\n- [ ] Test cross-department denial\n- [ ] Write test files"},
        4: {"area": "Security Review", "prefix": "SEC",
             "description": "Audit firewall, SSH logs, user accounts, service exposure, password policy.",
             "tasks": "- [ ] Review UFW rules\n- [ ] Check SSH logs for failures\n- [ ] Audit user accounts (userAccountControl)\n- [ ] Check listening ports\n- [ ] Review password policy"},
        5: {"area": "Monitoring", "prefix": "MON",
             "description": "Check monitoring dashboards, review alerts, document findings.",
             "tasks": "- [ ] Review Zabbix alerts\n- [ ] Review Wazuh alerts\n- [ ] Check disk space, memory, CPU\n- [ ] Document findings"},
        6: {"area": "Lab Maintenance", "prefix": "MAINT",
             "description": "Clean up old files, check disk space, review the week, plan next week.",
             "tasks": "- [ ] Remove old print jobs\n- [ ] Check disk space\n- [ ] Review week's tickets\n- [ ] Plan next week"},
    },
    2: {  # Week 2 — Infrastructure Expansion
        0: {"area": "Documentation", "prefix": "DOC",
             "description": "Update docs with changes from last week.",
             "tasks": "- [ ] Document DHCP setup\n- [ ] Document CUPS setup\n- [ ] Document file shares\n- [ ] Update change log"},
        1: {"area": "DHCP Management", "prefix": "DHCP",
             "description": "Add new DHCP scope for another VLAN, configure relay, test.",
             "tasks": "- [ ] Add subnet block to dhcpd.conf\n- [ ] Restart DHCP service\n- [ ] Configure router relay (ip helper)\n- [ ] Test with device on new VLAN"},
        2: {"area": "Print Server", "prefix": "PRINT",
             "description": "Add second printer, clean up old jobs, test printing.",
             "tasks": "- [ ] Add second virtual printer via CUPS web\n- [ ] Clean old PDF files\n- [ ] Test print from client\n- [ ] Check for stuck jobs"},
        3: {"area": "Backup Practice", "prefix": "BACK",
             "description": "Back up AD database, router config, service configs. Practice restore.",
             "tasks": "- [ ] Back up Samba AD\n- [ ] Back up router config\n- [ ] Back up service configs\n- [ ] Test restore of one backup"},
        4: {"area": "VPN Management", "prefix": "VPN",
             "description": "Start VPN, test connectivity, review config, practice key rotation.",
             "tasks": "- [ ] Start WireGuard on server and client\n- [ ] Verify handshake\n- [ ] Ping through tunnel\n- [ ] SSH through tunnel\n- [ ] Generate new keys and update configs"},
        5: {"area": "Monitoring", "prefix": "MON",
             "description": "Review alerts, check system health trends.",
             "tasks": "- [ ] Review Zabbix\n- [ ] Review Wazuh\n- [ ] Check disk, memory, CPU\n- [ ] Document trends"},
        6: {"area": "Lab Maintenance", "prefix": "MAINT",
             "description": "Clean up, review, plan.",
             "tasks": "- [ ] Clean up files\n- [ ] Review week\n- [ ] Plan Week 3"},
    },
    3: {  # Week 3 — Advanced Operations
        0: {"area": "Documentation", "prefix": "DOC",
             "description": "Full documentation review and refinement.",
             "tasks": "- [ ] Review all reference files\n- [ ] Verify accuracy\n- [ ] Update all change logs"},
        1: {"area": "Server Migration", "prefix": "MIGR",
             "description": "Plan and execute a service migration.",
             "tasks": "- [ ] Document current service config\n- [ ] Plan migration steps\n- [ ] Execute migration\n- [ ] Verify service works on new server"},
        2: {"area": "Patch Management", "prefix": "PATCH",
             "description": "Check for updates, install security updates, configure auto-updates.",
             "tasks": "- [ ] Check available updates\n- [ ] Install security updates\n- [ ] Configure unattended-upgrades\n- [ ] Verify services still running"},
        3: {"area": "Certificate Authority", "prefix": "CERT",
             "description": "Set up a simple CA with OpenSSL, generate and install certificates.",
             "tasks": "- [ ] Generate CA key and cert\n- [ ] Generate server CSR\n- [ ] Sign certificate with CA\n- [ ] Install cert in CUPS\n- [ ] Test HTTPS access"},
        4: {"area": "Security Hardening", "prefix": "HARD",
             "description": "Harden SSH, install fail2ban, test.",
             "tasks": "- [ ] Verify SSH key auth works\n- [ ] Disable password auth in sshd_config\n- [ ] Install and configure fail2ban\n- [ ] Test by triggering bans"},
        5: {"area": "Monitoring", "prefix": "MON",
             "description": "Review alerts, test fail2ban, check health.",
             "tasks": "- [ ] Review monitoring\n- [ ] Check fail2ban status\n- [ ] Review SSH attack patterns"},
        6: {"area": "Lab Maintenance", "prefix": "MAINT",
             "description": "Clean up, review Week 3, plan Week 4.",
             "tasks": "- [ ] Clean up\n- [ ] Review Week 3\n- [ ] Plan Week 4"},
    },
    4: {  # Week 4 — Mastery & Review
        0: {"area": "Documentation", "prefix": "DOC",
             "description": "Full review, update portfolio, ensure everything is current.",
             "tasks": "- [ ] Full documentation review\n- [ ] Update portfolio\n- [ ] Update resume with new skills"},
        1: {"area": "Disaster Recovery", "prefix": "DR",
             "description": "Simulate failures, diagnose, recover, document.",
             "tasks": "- [ ] Stop AD service, diagnose from client, fix\n- [ ] Stop DHCP, diagnose, fix\n- [ ] Delete a route, diagnose, fix\n- [ ] Document each recovery"},
        2: {"area": "Automation", "prefix": "AUTO",
             "description": "Write a morning checkup script, schedule with cron.",
             "tasks": "- [ ] Write bash script for health checks\n- [ ] Make executable\n- [ ] Test the script\n- [ ] Schedule with cron"},
        3: {"area": "Network Troubleshooting", "prefix": "NET",
             "description": "Simulate network issues, diagnose from client side, fix.",
             "tasks": "- [ ] Change router VLAN IP to wrong subnet, diagnose\n- [ ] Break DNS forwarder, diagnose\n- [ ] Remove DHCP relay, diagnose\n- [ ] Fix each issue and document"},
        4: {"area": "Full Audit", "prefix": "AUDIT",
             "description": "Complete security and configuration audit.",
             "tasks": "- [ ] Full user audit table\n- [ ] Full group audit\n- [ ] Full firewall audit\n- [ ] Full service audit\n- [ ] Full file share audit\n- [ ] DNS audit\n- [ ] Generate audit report"},
        5: {"area": "Monitoring", "prefix": "MON",
             "description": "Monthly monitoring review, compare weeks, look for trends.",
             "tasks": "- [ ] Compare weekly reports\n- [ ] Note recurring issues\n- [ ] Document monthly summary"},
        6: {"area": "Monthly Review", "prefix": "REVIEW",
             "description": "Review the month, update resume, plan next month.",
             "tasks": "- [ ] Review all tickets\n- [ ] List skills practiced\n- [ ] What was hard? What got easier?\n- [ ] Update resume\n- [ ] Plan next month"},
    },
}


def get_week_number(start_date, current_date):
    """Calculate which week of the rotation we're in (1-4, cycling)."""
    delta = current_date - start_date
    days = delta.days
    if days < 0:
        return 1
    week = (days // 7) + 1
    return ((week - 1) % 4) + 1


def generate_ticket(date, week, day_of_week):
    """Generate the daily ticket markdown content."""
    task = SCHEDULE[week][day_of_week]
    ticket_id = f"{task['prefix']}-{week:03d}"

    header = f"""# Daily Ticket — {date.strftime('%A')}, Week {week}

> **Date:** {date.strftime('%B %d, %Y')}
> **Priority:** Normal
> **Category:** {task['area']}
> **Description:** {task['description']}

---

"""

    body = f"""## Ticket: {ticket_id} — {task['area']}

**Description:** {task['description']}

### Tasks

{task['tasks']}
"""

    footer = END_OF_DAY.format(ticket_id=ticket_id)

    return header + MORNING_CHECKUP + body + footer


def main():
    now = datetime.now()
    week = get_week_number(START_DATE, now)
    day = now.weekday()

    os.makedirs(TICKETS_DIR, exist_ok=True)

    ticket_content = generate_ticket(now, week, day)

    task = SCHEDULE[week][day]
    ticket_id = f"{task['prefix']}-{week:03d}"
    day_name = now.strftime('%A')
    filename = f"{day_name}_Week{week}_{ticket_id}.md"
    filepath = os.path.join(TICKETS_DIR, filename)

    with open(filepath, 'w') as f:
        f.write(ticket_content)

    print(f"Daily ticket created: {filepath}")
    print(f"Week: {week}, Day: {day_name}, Task: {task['area']}")
    print(f"Ticket ID: {ticket_id}")


if __name__ == "__main__":
    main()
